import type { Page } from "@playwright/test";

const now = "2026-08-23T10:00:00.000Z";
const later = "2026-08-23T11:00:00.000Z";

export const schemaV2Vault = {
  schemaVersion: 2,
  vaultGroups: [
    {
      id: "session",
      name: "Session Aug 23 13:00",
      description: "Captured together",
      category: "session",
      accent: "#829b65",
      createdAt: later,
      updatedAt: later,
    },
    {
      id: "research",
      name: "Research",
      description: "Research material",
      category: "manual",
      accent: "#829b65",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "empty",
      name: "Empty shelf",
      description: "Kept explicitly",
      category: "custom-category",
      accent: "#829b65",
      createdAt: now,
      updatedAt: now,
    },
  ],
  tabs: [
    {
      id: "t-1001",
      groupId: null,
      title: "Agents can organize the web better than we can",
      url: "https://notes.example.com/agents?b=2&a=1#part",
      domain: "notes.example.com",
      note: "A useful framing for the agent-facing contract.",
      agentReview: "",
      viewed: false,
      tags: ["product"],
      color: "#EDB958",
      icon: "A",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "t-duplicate",
      groupId: "session",
      title: "Agents can organize the web better than we can",
      url: "https://notes.example.com/agents?b=2&a=1#part",
      domain: "notes.example.com",
      note: "A useful framing for the agent-facing contract.",
      agentReview: "",
      viewed: true,
      tags: ["Product", "merged"],
      color: "#EDB958",
      icon: "A",
      createdAt: later,
      updatedAt: later,
    },
    {
      id: "t-research",
      groupId: "research",
      title: "Model Context Protocol specification",
      url: "https://modelcontextprotocol.io/specification",
      domain: "modelcontextprotocol.io",
      note: "Reference implementation details.",
      agentReview: "",
      viewed: false,
      tags: ["mcp"],
      color: "#0e3c34",
      icon: "M",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "t-hidden",
      groupId: "research",
      title: "Hidden research",
      url: "https://example.com/hidden",
      domain: "example.com",
      note: "Come back later",
      agentReview: "",
      viewed: false,
      tags: [],
      color: "#6b8c7e",
      icon: "H",
      createdAt: now,
      updatedAt: now,
      hiddenUntil: "2999-01-01T00:00:00.000Z",
    },
    {
      id: "t-archived",
      groupId: null,
      title: "Archived reference",
      url: "https://example.com/archived",
      domain: "example.com",
      note: "Archived",
      agentReview: "",
      viewed: false,
      tags: [],
      color: "#6b8c7e",
      icon: "R",
      createdAt: now,
      updatedAt: now,
      archived: true,
      archivedAt: later,
      hiddenUntil: "2999-01-01T00:00:00.000Z",
    },
    {
      id: "advanced-old",
      groupId: null,
      title: "Old title",
      url: "https://example.com/exact?a=1#x",
      domain: "example.com",
      note: "Old note",
      agentReview: "old review",
      viewed: false,
      tags: ["shared", "old"],
      color: "#6b8c7e",
      icon: "O",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "advanced-new",
      groupId: "session",
      title: "New title",
      url: "https://example.com/exact?a=1#x",
      domain: "example.com",
      note: "New note",
      agentReview: "new review",
      viewed: true,
      tags: ["shared", "new"],
      color: "#6b8c7e",
      icon: "N",
      createdAt: later,
      updatedAt: later,
    },
  ],
  tagCatalog: { product: "Product", mcp: "Protocol", merged: "Merged" },
  tabOrders: {
    unassigned: ["t-1001", "advanced-old"],
    session: ["t-duplicate", "advanced-new"],
    research: ["t-research", "t-hidden"],
    empty: [],
  },
  savedSearches: [],
  tabView: "standard",
};

export async function openSchemaV2Library(page: Page) {
  await page.goto("/");
  await page.evaluate(vault => {
    localStorage.clear();
    localStorage.setItem("tabvault-v2", JSON.stringify(vault));
  }, schemaV2Vault);
  await page.reload();
  await page.getByTestId("tab-row-t-1001").waitFor();
}
